### ISSUE TITLE
How should I be returning the size with completion handler?

### ISSUE THREAD

**Issue by rlam3** [IMcD23/IMRemoteImageSize#1]
Hi, 

I'm using https://github.com/ecerney/CollectionViewWaterfallLayout and need IMRemoteImageSize to return the async size before I return the size to collectionviewwaterfalllayout. 

``` swift


func collectionView(collectionView: UICollectionView, layout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {

        let image = images[indexPath.row]

        var sizeOfTopCover:CGSize?

        var image = UIImage.getImageSize(image.url, completion: {


            (size) -> Void in
            print("Got size of image: \(image.url): \(size)")

            sizeOfTopCover = size

        })

        return sizeOfTopCover! <<< breaking here

    }

```

It keeps returning "nil" 

Thanks for your help!

**Comment by ian-mcdowell** [comment]
Sorry for the delay. The code in the completion block will be executed after the return statement. I would suggest finding the image size before the sizeForItemAtIndexPath: method is called.
